config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :centros do
  resources :alumnos 
  end
   root to: 'centros#index'

    get'/alumnos', to: 'alumnos#index', as: 'alumnos'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alumno.rb
class Alumno < ApplicationRecord
    belongs_to :centro
    mount_uploader :avatar, FotoUploader
end

app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  before_action :set_alumno, only: [:show, :edit, :update, :destroy]

  # GET /alumnos
  # GET /alumnos.json
  def index
    @alumnos = Alumno.all
  end

  # GET /alumnos/1
  # GET /alumnos/1.json
  def show
  end

  # GET /alumnos/new
  def new
    @alumno = Alumno.new
  end

  # GET /alumnos/1/edit
  def edit
  end

  # POST /alumnos
  # POST /alumnos.json
  def create
   @centro = Centro.find(params[:centro_id]);
    @alumno = @centro.alumnos.create(alumno_params)

    respond_to do |format|
      if @alumno.save
        format.html { redirect_to @alumno, notice: 'Alumno was successfully created.' }
        format.json { render :show, status: :created, location: @alumno }
        format.js
      else
        format.html { render :new }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnos/1
  # PATCH/PUT /alumnos/1.json
  def update
    respond_to do |format|
      if @alumno.update(alumno_params)
        format.html { redirect_to @alumno, notice: 'Alumno was successfully updated.' }
        format.json { render :show, status: :ok, location: @alumno }
      else
        format.html { render :edit }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1
  # DELETE /alumnoszz/1.json
  def destroy
    @alumno.destroy
    respond_to do |format|
      format.html { redirect_to alumnos_url, notice: 'Alumno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumno
      @alumno = Alumno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alumno_params
      params.require(:alumno).permit(:nombre, :apellido, :edad, :telefono, :centro_id, :avatar)
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/views/alumnos/_alumno.html.erb
<%= div_for alumno do %>

	<p id="notice"><%= notice %></p>
<table>
  <thead>
  </thead>
  <tbody>
   
      <tr>
        <td width=16%><%= image_tag(alumno.avatar, :width => 75, :height => 65)  %> </td>
        <td width=16%><%= alumno.nombre %></td>
        <td width=16%><%= alumno.apellido %></td>
        <td width=16%><%= alumno.edad %></td>
        <td width=16%><%= alumno.telefono %></td>
       
        <td width=16%><%= time_ago_in_words(alumno.created_at)%></td>
      </tr>
    
  </tbody>
</table>
<% end %>

app/views/alumnos/_form.html.erb
<%= form_for(alumno) do |f| %>
  <% if alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alumno.errors.count, "error") %> prohibited this alumno from being saved:</h2>

      <ul>
      <% alumno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :apellido %>
    <%= f.text_field :apellido %>
  </div>

  <div class="field">
    <%= f.label :edad %>
    <%= f.number_field :edad %>
  </div>

  <div class="field">
    <%= f.label :telefono %>
    <%= f.number_field :telefono %>
  </div>

  <div class="field">
    <%= f.label :centro_id %>
    <%= f.number_field :centro_id %>
  </div>

   <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
    <div>
    

  <div class="actions">
    <%= f.submit %>
  </div>

   
<% end %>

app/views/alumnos/create.js.erb
var new_alumno =$("<%= escape_javascript(render(:partial =>@alumno))%>").hide();
$('#alumnos').prepend(new_alumno);
$('#alumno_<%=@alumno.id%>').fadeIn('slow');
$('#new_alumno')[0].reset();

app/views/alumnos/edit.html.erb
<h1>Editing Alumno</h1>

<%= render 'form', alumno: @alumno %>

<%= link_to 'Show', @alumno %> |
<%= link_to 'Back', alumnos_path %>

app/views/alumnos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alumnos</h1>

<table>
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Edad</th>
      <th>Telefono</th>
      <th>Centro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alumnos.each do |alumno| %>
      

      <tr>
        <td><%= image_tag(alumno.avatar_url, :width => 75, :height => 65)if alumno.avatar.present?  %></td>
        <td><%= alumno.nombre %></td>
        <td><%= alumno.apellido %></td>
        <td><%= alumno.edad %></td>
        <td><%= alumno.telefono %></td>
        <td><%= alumno.centro_id %></td>
        <td><%= link_to 'Show', alumno %></td>
        <td><%= link_to 'Edit', edit_alumno_path(alumno) %></td>
        <td><%= link_to 'Destroy', alumno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alumno', new_alumno_path %>

app/views/alumnos/new.html.erb
<h1>New Alumno</h1>

<%= render 'form', alumno: @alumno %>

<%= link_to 'Back', alumnos_path %>

app/views/alumnos/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Nombre:</strong>
  <%= @alumno.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @alumno.apellido %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @alumno.edad %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @alumno.telefono %>
</p>

<p>
  <strong>Centro:</strong>
  <%= @alumno.centro_id %>
</p>

<%= link_to 'Edit', edit_alumno_path(@alumno) %> |
<%= link_to 'Back', alumnos_path %>