config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :centros do
  resources :alumnos 
  end
   root to: 'centros#index'

    get'/alumnos', to: 'alumnos#index', as: 'alumnos'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/centro.rb
class Centro < ApplicationRecord
    has_many :alumnos
end

app/controllers/centros_controller.rb
class CentrosController < ApplicationController
  before_action :set_centro, only: [:show, :edit, :update, :destroy]

  # GET /centros
  # GET /centros.json
  def index
    @centros = Centro.all
  end

  # GET /centros/1
  # GET /centros/1.json
  def show
  end

  # GET /centros/new
  def new
    @centro = Centro.new
  end

  # GET /centros/1/edit
  def edit
  end

  # POST /centros
  # POST /centros.json
  def create
     @centro = Centro.new(centro_params)
     @centro.user_id = current_user.id

    respond_to do |format|
      if @centro.save
        format.html { redirect_to @centro, notice: 'Centro was successfully created.' }
        format.json { render :show, status: :created, location: @centro }
      else
        format.html { render :new }
        format.json { render json: @centro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centros/1
  # PATCH/PUT /centros/1.json
  def update
    respond_to do |format|
      if @centro.update(centro_params)
        format.html { redirect_to @centro, notice: 'Centro was successfully updated.' }
        format.json { render :show, status: :ok, location: @centro }
      else
        format.html { render :edit }
        format.json { render json: @centro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centros/1
  # DELETE /centros/1.json
  def destroy
    @centro.destroy
    respond_to do |format|
      format.html { redirect_to centros_url, notice: 'Centro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_centro
      @centro = Centro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def centro_params
      params.require(:centro).permit(:nombre, :direccion, :email, :user_id)
    end
end

app/helpers/centros_helper.rb
module CentrosHelper
end

app/views/centros/_form.html.erb
<%= form_for(centro) do |f| %>
  <% if centro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(centro.errors.count, "error") %> prohibited this centro from being saved:</h2>

      <ul>
      <% centro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :direccion %>
    <%= f.text_field :direccion %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>


  
<% end %>

app/views/centros/edit.html.erb
<h1>Editing Centro</h1>

<%= render 'form', centro: @centro %>

<%= link_to 'Show', @centro %> |
<%= link_to 'Back', centros_path %>

app/views/centros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Centros</h1>

<table>
  <thead>
    <tr>
    
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Email</th>ok
      <th colspan="3"></th>
      
    </tr>
  </thead>

  <tbody>
    <% @centros.each do |centro| %>
      <tr>
         <td><%= centro.nombre %></td>
        <td><%= centro.direccion %></td>
        <td><%= centro.email %></td>
        <td><%= link_to 'Show', centro,  class:"info button round" %></td>
        <td><%= link_to 'Edit', edit_centro_path(centro),  class:"button round" %></td>
        <td><%= link_to 'Destroy', centro, method: :delete, class:"button round alert", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Centro', new_centro_path, class:" success radius button" %>

app/views/centros/new.html.erb
<h1>New Centro</h1>

<%= render 'form', centro: @centro %>

<%= link_to 'Back', centros_path %>

app/views/centros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @centro.nombre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @centro.direccion %>
</p>

<p>
  <strong>Email:</strong>
  <%= @centro.email %>
</p>
<table>
<thead>

    <tr>
      <th width=16%>Perfil</th>
      <th width=16%>Nombre</th>
      <th width=16%>Apellido</th>
      <th width=16%>Edad</th>
      <th width=16%>Telefono</th>
      <th width=16%>Agregado</th>
      <th colspan="3"></th>
    </tr> 

  </thead>
</table> 




<div id="alumnos">
  <%= render :partial => @centro.alumnos.reverse %>
</div>

<%= form_for([@centro, Alumno.new], remote: true) do |f| %>

<div class="field">
  <%= f.label :Foto %>
   <%= f.file_field :avatar %>
</div>

<div class="field">
  <%= f.label :Nombre %>
  <%= f.text_field :nombre %>
   
</div>

<div class="field">
  <%= f.label :Apellido %>
   <%= f.text_field :apellido %>
</div>

<div class="field">
  <%= f.label :Edad %>
   <%= f.number_field :edad %>
</div>
<div class="field">
  <%= f.label :Telefono %>
   <%= f.text_field :telefono %>
</div>

<div class="actions">
  <%= f.submit "Agregar Alumno", class:" success radius button" %>
</div>
<% end %>

<%= link_to 'Edit', edit_centro_path(@centro), class:"tiny button round" %> |
<%= link_to 'Back', centros_path, class:"tiny button round" %>