config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :centros do
  resources :alumnos 
  end
   root to: 'centros#index'

    get'/alumnos', to: 'alumnos#index', as: 'alumnos'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="centros">CLEM</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li class="active"><a href=http://localhost:3000/centros/4>LIDER</a></li>
      <li class="has-dropdown">
        <a href="#">Siguenos</a>
        <ul class="dropdown">
          <li><a href=https://www.facebook.com/CLEMLiderazgo/>Facebook</a></li>
          <li class="active"><a href=https://twitter.com/CLEM_Falco>Twitter</a></li>

        </ul>
      </li>
    </ul>
    <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#"Right Button Active</a></li>
 <% if admin_signed_in? %> 
    <li> Bienvenido(a) <%= current_admin.email %></li>
    <li><%= link_to 'Edit profile', edit_admin_registration_path %></li>
    <li><%= link_to 'Logout', destroy_admin_session_path, method: :delete %></li>
 </ul>
  </li>
   <% elsif user_signed_in? %>
   <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#"Right Button Active</a></li>
    <li> Bienvenido(a) <%= current_user.email %></li>
    <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Login',  new_user_session_path %></li>
      <li><%= link_to 'Signup',  new_user_registration_path %></li>
    <% end %>
    
  </ul>
  </li>

</div>
</div>
</div>
</div>

 </section>
</nav>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>